name: auto-app2-env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  
  - bwa=0.7.17
  - samtools=1.9
  
  - pysam=0.16.0
  - tqdm=4.64.0
  - requests=2.31.0
  - numpy=1.19.5
  - pandas=1.3.5
  
  - pip
  - pip:
    - pathlib2>=2.3.5
    - certifi>=2024.7.4
    - charset-normalizer>=3.3.2
    - idna>=3.7
    - urllib3>=2.2.2
    - psutil>=5.9.5
    - colorama>=0.4.6